@baseUrl = http://localhost:3000/api/agenda
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWRfcGVyYW4iOjEsImlhdCI6MTc1MDc3MTQzMSwiZXhwIjoxNzUwODU3ODMxfQ.L-2hH4cOTqBqc1u7PBIJeyfJGDLC-WW--FLyWSjdEnA

### GET semua agenda
GET {{baseUrl}}
Authorization: Bearer {{token}}

### GET agenda by ID
GET {{baseUrl}}/1
Authorization: Bearer {{token}}

### POST tambah agenda
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "judul_kegiatan": "Rapat Warga RT Test",
  "tanggal": "2025-07-05",
  "waktu": "19:30:00",
  "lokasi": "Balai Warga RT 03",
  "deskripsi": "Agenda musyawarah warga membahas kebersihan lingkungan.",
  "jenis_kegiatan": "Sosial",
  "id_konten": 6
}

### PUT update agenda
PUT {{baseUrl}}/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "judul_kegiatan": "Rapat Warga RT 03 - Update",
  "tanggal": "2025-07-06",
  "waktu": "20:00:00",
  "lokasi": "Balai Warga RT 03",
  "deskripsi": "Perubahan waktu rapat karena hujan.",
  "jenis_kegiatan": "Sosial",
  "id_konten": null
}

### DELETE agenda
DELETE {{baseUrl}}/1
Authorization: Bearer {{token}}
