@baseUrl = http://localhost:3000/api/dokumen
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWRfcGVyYW4iOjEsImlhdCI6MTc1MDc3MjIyNywiZXhwIjoxNzUwODU4NjI3fQ.N9c2XiTiyNb1IZrTzCoAntu1JXfG1vOyiY_-8unVmLw

### GET semua dokumen
GET {{baseUrl}}
Authorization: Bearer {{token}}

### GET dokumen by ID
GET {{baseUrl}}/1
Authorization: Bearer {{token}}

### POST tambah dokumen
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "judul": "Peraturan Desa Tentang Kebersihan",
  "tanggal_dokumen": "2025-06-01",
  "lokasi_file": "uploads/dokumen/perdes-kebersihan.pdf",
  "kategori": "Regulasi"
}

### PUT update dokumen
PUT {{baseUrl}}/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "judul": "Perdes Kebersihan Lingkungan (Update)",
  "tanggal_dokumen": "2025-06-02",
  "lokasi_file": "uploads/dokumen/perdes-kebersihan-update.pdf",
  "kategori": "Regulasi"
}

### DELETE dokumen
DELETE {{baseUrl}}/1
Authorization: Bearer {{token}}
