@baseUrl = http://localhost:3000/api/profil-desa
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWRfcGVyYW4iOjEsImlhdCI6MTc1MDk1NTYwMCwiZXhwIjoxNzUxMDQyMDAwfQ.ljfUpS9xXpxhwrmf9CF-N8Frs1LxeCYQsSbNxWOvaoQ

### GET semua profil
GET {{baseUrl}}

### GET profil by ID
GET {{baseUrl}}/1

### POST tambah profil
POST {{baseUrl}}ß
Content-Type: application/json
Authorization: {{token}}

{
  "bagian": "Sejarah",
  "judul": "Sejarah Desa Cengkilung",
  "konten": "Desa Cengkilung berdiri sejak tahun 1800...",
  "lokasi_gambar": "uploads/profil/sejarah.jpg",
  "urutan_tampil": 1
}

### PUT update profil
PUT {{baseUrl}}/1
Content-Type: application/json
Authorization: {{token}}

{
  "bagian": "Sejarah",
  "judul": "Sejarah Desa Cengkilung (Update)",
  "konten": "Diperbarui: Desa ini berdiri sejak abad ke-18...",
  "lokasi_gambar": "uploads/profil/sejarah-update.jpg",
  "urutan_tampil": 1
}

### DELETE profil
DELETE {{baseUrl}}/1
Authorization: {{token}}
