@baseUrl = http://localhost:3000/api
@token = Bearer <token_opsional_kalau_login>

###  GET 3 Sejarah Terbaru
GET {{baseUrl}}/sejarah
Authorization: {{token}}

###  GET Dokumentasi Sejarah (thumbnail dan judul)
GET {{baseUrl}}/sejarah/galeri
Authorization: {{token}}

###  GET 3 Sejarah Terbaru
GET {{baseUrl}}/sejarah


###  GET Dokumentasi Sejarah (thumbnail dan judul)
GET {{baseUrl}}/sejarah/galeri

